#
# Copyright (c) 2026 Haoting Ying (zzsqjdhqgb). All rights reserved.
# Proprietary code. Use is subject to the LICENSE file in the repository root.
#

singleQuote: true
semi: false
printWidth: 100
trailingComma: none
endOfLine: crlf
