export const AIROUTER_CHANNELS = {
  listConfigs: 'airouter:list-configs',
  saveConfig: 'airouter:save-config',
  deleteConfig: 'airouter:delete-config',
  readApiKey: 'airouter:read-api-key',
  listModels: 'airouter:list-models',
  testConnection: 'airouter:test-connection',
  listImageConfigs: 'airouter:list-image-configs',
  saveImageConfig: 'airouter:save-image-config',
  deleteImageConfig: 'airouter:delete-image-config',
  readImageApiKey: 'airouter:read-image-api-key',
  listImageModels: 'airouter:list-image-models',
  testImageConnection: 'airouter:test-image-connection',
  imageGenerateStart: 'airouter:image-generate-start',
  imageGenerateAbort: 'airouter:image-generate-abort',
  imageGenerateEvent: 'airouter:image-generate-event',
  listSpeechConfigs: 'airouter:list-speech-configs',
  saveSpeechConfig: 'airouter:save-speech-config',
  deleteSpeechConfig: 'airouter:delete-speech-config',
  readSpeechApiKey: 'airouter:read-speech-api-key',
  listSpeechPackages: 'airouter:list-speech-packages',
  importSpeechPackage: 'airouter:import-speech-package',
  deleteSpeechPackage: 'airouter:delete-speech-package',
  listSpeechModels: 'airouter:list-speech-models',
  listSpeechVoices: 'airouter:list-speech-voices',
  testSpeechConnection: 'airouter:test-speech-connection',
  speechSynthesisStart: 'airouter:speech-synthesis-start',
  speechSynthesisAbort: 'airouter:speech-synthesis-abort',
  speechSynthesisEvent: 'airouter:speech-synthesis-event',
  listRecognitionModels: 'airouter:list-recognition-models',
  listRecognitionConfigs: 'airouter:list-recognition-configs',
  saveRecognitionConfig: 'airouter:save-recognition-config',
  deleteRecognitionConfig: 'airouter:delete-recognition-config',
  readRecognitionApiKey: 'airouter:read-recognition-api-key',
  listRecognitionPackages: 'airouter:list-recognition-packages',
  importRecognitionPackage: 'airouter:import-recognition-package',
  deleteRecognitionPackage: 'airouter:delete-recognition-package',
  listRecognitionProviderModels: 'airouter:list-recognition-provider-models',
  speechRecognitionStart: 'airouter:speech-recognition-start',
  speechRecognitionAbort: 'airouter:speech-recognition-abort',
  speechRecognitionEvent: 'airouter:speech-recognition-event',
  listPronunciationModels: 'airouter:list-pronunciation-models',
  pronunciationAssessmentStart: 'airouter:pronunciation-assessment-start',
  pronunciationAssessmentAbort: 'airouter:pronunciation-assessment-abort',
  pronunciationAssessmentEvent: 'airouter:pronunciation-assessment-event',
  generateStart: 'airouter:generate-start',
  generateAbort: 'airouter:generate-abort',
  generateEvent: 'airouter:generate-event'
} as const

export const BUILTIN_PRONUNCIATION_PROVIDER_ID = 'builtin-facebook-phoneme'
export const BUILTIN_PRONUNCIATION_MODEL_ID = 'wav2vec2-lv-60-espeak-cv-ft-int8-c69750f'

export type AIRouterChannel = (typeof AIROUTER_CHANNELS)[keyof typeof AIROUTER_CHANNELS]
