Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vm.hostname = "cyez-ls101-dev"

  project_root = File.expand_path("..", __dir__)

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder project_root, "/workspace-mount"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "cyez-ls101-dev"
    vb.memory = 4096
    vb.cpus = 6
  end

  config.vm.provision "shell", path: "provision.sh"
end